#!/usr/bin/env bash
set -euo pipefail

PROJECT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
DEPLOY_DIR="$PROJECT_DIR/deploy"
CONFIG_PATH="$DEPLOY_DIR/cloudflared-config.yml"
LAUNCHD_TEMPLATE_PATH="$PROJECT_DIR/launchd/com.hyuga.leftcontroller.cloudflared.plist"

TUNNEL_NAME="${TUNNEL_NAME:-left-controller}"
DOMAIN="${DOMAIN:-}"
CREDENTIALS_FILE="${CREDENTIALS_FILE:-}"

usage() {
  cat <<USAGE
Usage:
  bash deploy/setup-cloudflare.sh --domain <domain> --credentials-file <path> [--tunnel-name <name>]

Example:
  bash deploy/setup-cloudflare.sh \\
    --domain controller.example.com \\
    --credentials-file /Users/$USER/.cloudflared/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx.json \\
    --tunnel-name left-controller
USAGE
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --domain)
      DOMAIN="$2"
      shift 2
      ;;
    --credentials-file)
      CREDENTIALS_FILE="$2"
      shift 2
      ;;
    --tunnel-name)
      TUNNEL_NAME="$2"
      shift 2
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown option: $1" >&2
      usage
      exit 1
      ;;
  esac
done

if [[ -z "$DOMAIN" || -z "$CREDENTIALS_FILE" ]]; then
  echo "--domain and --credentials-file are required." >&2
  usage
  exit 1
fi

if ! command -v cloudflared >/dev/null 2>&1; then
  echo "cloudflared is not installed. Install it first:" >&2
  echo "  brew install cloudflared" >&2
  exit 1
fi

if [[ ! -f "$CREDENTIALS_FILE" ]]; then
  echo "credentials file not found: $CREDENTIALS_FILE" >&2
  exit 1
fi

mkdir -p "$DEPLOY_DIR"

cat > "$CONFIG_PATH" <<CFG
# Auto-generated by deploy/setup-cloudflare.sh
# Generated at: $(date -u +"%Y-%m-%dT%H:%M:%SZ")

tunnel: $TUNNEL_NAME
credentials-file: $CREDENTIALS_FILE

ingress:
  - hostname: $DOMAIN
    service: http://localhost:8080
  - service: http_status:404
CFG

cat > "$LAUNCHD_TEMPLATE_PATH" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>com.hyuga.leftcontroller.cloudflared</string>

  <key>ProgramArguments</key>
  <array>
    <string>/usr/bin/env</string>
    <string>cloudflared</string>
    <string>tunnel</string>
    <string>--config</string>
    <string>$CONFIG_PATH</string>
    <string>run</string>
  </array>

  <key>WorkingDirectory</key>
  <string>$PROJECT_DIR</string>

  <key>RunAtLoad</key>
  <true/>

  <key>KeepAlive</key>
  <true/>

  <key>StandardOutPath</key>
  <string>$PROJECT_DIR/logs/cloudflared.log</string>

  <key>StandardErrorPath</key>
  <string>$PROJECT_DIR/logs/cloudflared.log</string>
</dict>
</plist>
PLIST

mkdir -p "$PROJECT_DIR/logs"

echo "Generated:"
echo "  - $CONFIG_PATH"
echo "  - $LAUNCHD_TEMPLATE_PATH"
echo
echo "Next commands:"
echo "  cloudflared tunnel route dns $TUNNEL_NAME $DOMAIN"
echo "  bash deploy/install-launchd.sh"
